export class CreatePhongDto {
    id:0;
    ten_phong:string;
    khach:number
    phong_ngu:number;
    phong_tam:number;
    mo_ta:string;
    gia_tien:number;
    may_giat:boolean;
    ban_la:boolean;
    tivi:boolean;
    dieu_hoa:boolean;
    wifi:boolean;
    bep:boolean;
    do_xe:boolean;
    ho_boi:boolean;
    ban_ui:boolean;
    hinh_anh:string
}
